### ISSUE TITLE
Could not connect to MB Websocket

### ISSUE THREAD

**Issue by steeve** [ReneNulschDE/mbapi2020#98]
Hi,

The component used to work fine, but for some time now, it's failing with the following error:

```
Could not connect to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws, retry in 10 seconds...
```

I have tried deleting/restarting/reauthenticating multiple times, no to avail. When setuping, the vehicle is correctly detected, but no entities are created/found.

Thank you again for this great component!

**Comment by ReneNulschDE** [comment]
Hi,

Make sure you are running on >=HA2022.11 and MBAPI2020 =v0.7.4

Then:

    please delete the .Mercedes token file in your HA folder
    Restart HA
    Reauthenticate the component

**Comment by steeve** [comment]
Thanks for the reply.

I am running everything to the latest and did try to reauthenticate multiple times by either reinstalling the component and restarting or removing the token cache file.

I am running HA=2022.12.9 and MBAPI2020=v0.7.4.

**Comment by ReneNulschDE** [comment]
could you please enable the debug logging (see readme) and send the log to mbapi2020-i98 (at) nulsch . de

**Comment by MarcW22** [comment]
As i have the same issue i send you my log.

**Comment by ReneNulschDE** [comment]
hi @MarcW22,

the debug log for the MBAPI2020 component was not enabled. Please enable it before sharing the log via email (address: mbapi2020-i98 (at) nulsch . de)


configuration.yaml:

logger:
  default: warn
  logs:
    custom_components.mbapi2020: debug

**Comment by MathieuWuyts** [comment]
Same problem with me.

**Comment by ReneNulschDE** [comment]
Hi @MathieuWuyts ,

please share some more information. Are you running on the latest version? What is your region. Please enable debug logging and share the log via email (address: mbapi2020-i98 (at) nulsch . de)

You can attach the diagnostic information (HA, integrations, click on the 3 dots of the MB component and download the diagnostic)

**Comment by ReneNulschDE** [comment]
Hi @MathieuWuyts ,

I have published a version v0.8.0 and besides the long list of changes, I added a better Error-reporting for your case, when the component log level is set to debug. Could you please check again and share the error message? And please make sure that your MB mobile app is working and that you see the status changes in the app. The problem from MarcW22 was a different one and was solved via mail.

**Comment by steeve** [comment]
Hey Rene, apologies for the late reply, here is my debug log with 0.8.0:

```
2023-01-08 23:00:46.450 INFO (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2023-01-08 23:00:46.450 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2023-01-08 23:00:46.451 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2023-01-08 23:00:47.096 DEBUG (MainThread) [custom_components.mbapi2020] VIN not found in masterdata. Used FIN XXXXXXXXXXX instead.
2023-01-08 23:00:47.096 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2023-01-08 23:00:47.434 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2023-01-08 23:00:47.640 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2023-01-08 23:00:48.066 DEBUG (MainThread) [custom_components.mbapi2020] RCP supported for car XXXXXXXXXXX: True
2023-01-08 23:00:48.066 DEBUG (MainThread) [custom_components.mbapi2020] Init - car added - XXXXXXXXXXXXXXX
2023-01-08 23:00:48.066 DEBUG (MainThread) [custom_components.mbapi2020.client] start update_poll_states
2023-01-08 23:00:48.066 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2023-01-08 23:00:48.410 DEBUG (MainThread) [custom_components.mbapi2020.api] Traceback (most recent call last):
  File "/config/custom_components/mbapi2020/api.py", line 84, in _request
2023-01-08 23:00:48.410 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2023-01-08 23:00:48.411 INFO (MainThread) [custom_components.mbapi2020.websocket] Connecting to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws
2023-01-08 23:00:48.553 ERROR (MainThread) [custom_components.mbapi2020.websocket] Could not connect to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws, retry in 10 seconds...
2023-01-08 23:00:48.555 DEBUG (MainThread) [custom_components.mbapi2020.websocket] 403, message='Invalid response status', url=URL('wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws')
2023-01-08 23:00:58.556 INFO (MainThread) [custom_components.mbapi2020.websocket] Connecting to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws
2023-01-08 23:00:58.568 ERROR (MainThread) [custom_components.mbapi2020.websocket] Could not connect to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws, retry in 10 seconds...
2023-01-08 23:00:58.569 DEBUG (MainThread) [custom_components.mbapi2020.websocket] 403, message='Invalid response status', url=URL('wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws')
2023-01-08 23:01:08.570 INFO (MainThread) [custom_components.mbapi2020.websocket] Connecting to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws
2023-01-08 23:01:08.583 ERROR (MainThread) [custom_components.mbapi2020.websocket] Could not connect to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws, retry in 10 seconds...
2023-01-08 23:01:08.584 DEBUG (MainThread) [custom_components.mbapi2020.websocket] 403, message='Invalid response status', url=URL('wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws')
```

**Comment by steeve** [comment]
Here are the diagnostics, and `cars` entry properly formatted:

```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.1.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "5.15.80",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "mbapi2020": {
      "version": "0.8.0",
      "requirements": [
        "protobuf>=3.19.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "mbapi2020",
    "name": "MercedesME 2020",
    "config_flow": true,
    "documentation": "https://github.com/ReneNulschDE/mbapi2020",
    "issue_tracker": "https://github.com/ReneNulschDE/mbapi2020/issues",
    "requirements": [
      "protobuf>=3.19.1"
    ],
    "dependencies": [],
    "codeowners": [
      "@ReneNulschDE"
    ],
    "version": "0.8.0",
    "iot_class": "cloud_push",
    "integration_type": "hub",
    "loggers": [
      "custom_components.mbapi2020"
    ],
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "XXXXXXX",
      "version": 1,
      "domain": "mbapi2020",
      "title": "mbapi2020",
      "data": {
        "username": "**REDACTED**",
        "region": "Europe",
        "nonce": "XXXXXXXX",
        "token": {
          "access_token": "**REDACTED**",
          "refresh_token": "**REDACTED**",
          "token_type": "Bearer",
          "expires_in": 7199,
          "expires_at": 1673222353
        }
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "cars": "...."
  }
}
```

`cars`:
```
[
  {
    "licenseplate": "XXXXXXXXXXX",
    "finorvin": "XXXXXXXXXXX",
    "_is_owner": null,
    "messages_received": {
      "f": 0,
      "p": 0
    },
    "_last_message_received": 1673215248066,
    "_last_command_type": "",
    "_last_command_state": "",
    "_last_command_error_code": "",
    "_last_command_error_message": "",
    "_last_command_time_stamp": 0,
    "binarysensors": null,
    "tires": null,
    "odometer": null,
    "doors": null,
    "location": null,
    "windows": null,
    "features": {
      "name": "Features",
      "ZEV_PRECONDITION_CONFIGURE": false,
      "ZEV_PRECONDITION_CONFIGURE_SEATS": false,
      "ZEV_PRECONDITIONING_START": false,
      "ZEV_PRECONDITIONING_STOP": false,
      "AUXHEAT_CONFIGURE": false,
      "AUXHEAT_START": false,
      "AUXHEAT_STOP": false,
      "BATTERY_CHARGE_PROGRAM_CONFIGURE": false,
      "BATTERY_MAX_SOC_CONFIGURE": false,
      "CHARGE_OPT_CONFIGURE": false,
      "CHARGE_OPT_START": false,
      "CHARGE_OPT_STOP": false,
      "CHARGE_PROGRAM_CONFIGURE": false,
      "DOORS_LOCK": true,
      "DOORS_UNLOCK": true,
      "ENGINE_START": false,
      "ENGINE_STOP": false,
      "SUNROOF_OPEN": true,
      "SUNROOF_LIFT": true,
      "SUNROOF_CLOSE": true,
      "SPEEDALERT_START": false,
      "SPEEDALERT_STOP": false,
      "TEMPERATURE_CONFIGURE": false,
      "THEFTALARM_DESELECT_INTERIOR": false,
      "THEFTALARM_DESELECT_TOW": false,
      "THEFTALARM_SELECT_INTERIOR": false,
      "THEFTALARM_SELECT_TOW": false,
      "THEFTALARM_START": false,
      "THEFTALARM_STOP": false,
      "THEFTALARM_CONFIRM_DAMAGEDETECTION": false,
      "THEFTALARM_DESELECT_DAMAGEDETECTION": false,
      "THEFTALARM_SELECT_DAMAGEDETECTION": false,
      "WEEK_PROFILE_CONFIGURE": false,
      "WINDOWS_OPEN": true,
      "WINDOWS_CLOSE": true,
      "WINDOWS_VENTILATE": false,
      "WIPER_HEALTH_RESET": false,
      "SIGPOS_START": true
    },
    "rcp_options": {
      "name": "RCP_Options",
      "rcp_supported": {
        "value": true,
        "retrievalstatus": "VALID",
        "timestamp": 0,
        "distance_unit": null,
        "display_value": null,
        "unit": null
      }
    },
    "auxheat": null,
    "precond": null,
    "electric": null,
    "caralarm": null,
    "geofence_events": {
      "name": "GeofenceEvents",
      "events": []
    },
    "entry_setup_complete": false,
    "_update_listeners": []
  }
]
```

**Comment by iHaveAstream** [comment]
Hi,

since yesterday evening I've the very same issue.
However, controlling or monitoring the car thru HA is still possible. Couldn't yet notice any restrictions related to the error.


`This error originated from a custom integration.

Logger: custom_components.mbapi2020.websocket
Source: custom_components/mbapi2020/websocket.py:132
Integration: MercedesME 2020 (documentation, issues)
First occurred: January 9, 2023 at 20:07:31 (4061 occurrences)
Last logged: 07:26:12

Could not connect to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws, retry in 10 seconds...`

Using latest version of the custom integration on HA 2023.1.1

BR,
Stefan

**Comment by ReneNulschDE** [comment]
Original problem from Steeve was solved by the MB-Support as the MB-app was not working too. They created a new MBme account at the car dealer.

**Comment by steeve** [comment]
Hi Rene,
I am not using a proxy, and tried changing DNSs multiple times juste in case. The app doesn't report any error either, but I haven't tried using the fonctions as the car doesn't have connectivity at the moment.
I am still experiencing connection issues.
